config/routes.rb
PortfolioSite::Application.routes.draw do
  resources :resume
  resources :home

  root to: "home#index"
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/resume.rb
class Resume < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /home
  # GET /home.json
  def index
    @home = Home.all
  end

  # GET /home/1
  # GET /home/1.json
  def show
  end

  # GET /home/new
  def new
    @home = Home.new
  end

  # GET /home/1/edit
  def edit
  end

  # POST /home
  # POST /home.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render action: 'show', status: :created, location: @home }
      else
        format.html { render action: 'new' }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /home/1
  # PATCH/PUT /home/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /home/1
  # DELETE /home/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to home_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params[:home]
    end
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]

  # GET /resume
  # GET /resume.json
  def index
    @resume = Resume.all
    redirect_to "https://s3-us-west-1.amazonaws.com/jacksonsandlandportfolio/Resume.pdf"
  end

  # GET /resume/1
  # GET /resume/1.json
  def show
  end

  # GET /resume/new
  def new
    @resume = Resume.new
  end

  # GET /resume/1/edit
  def edit
  end

  # POST /resume
  # POST /resume.json
  def create
    @resume = Resume.new(resume_params)

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
        format.json { render action: 'show', status: :created, location: @resume }
      else
        format.html { render action: 'new' }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /resume/1
  # PATCH/PUT /resume/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resume/1
  # DELETE /resume/1.json
  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resume_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params[:resume]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/views/home/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/home/edit.html.erb
<h1>Editing home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', home_index_path %>

app/views/home/index.html.erb
<header>
<div class="top_border">
</div>
<div class="inline">
<%= image_tag("portrait.png", :alt => "portrait", :class => "portrait_dimension") %>
</div>
<div class="container text_align">
<h1>Jackson Sandland</h1>
<h2>Full Stack Web Developer and Music Producer</h2>
<%= link_to "Github  /", "https://github.com/jackson-sandland", { :class=>"text_decoration" } %>
<%= link_to "Linked-In  /", "https://linkedin.com/in/jacksonsandland/", { :class=>"text_decoration" } %>
<%= link_to "Resume", "/assets/images/Resume.pdf", { :class=>"text_decoration" } %>
</div>
</header>
<!doctype html>
<html>
<head>
  <meta name="viewport" content="width=device-width">

</head>
<body>
  <div class="container">
    <div id="slides">
    <%= image_tag("example-slide-1.jpg") %>
    <%= image_tag("example-slide-2.jpg") %>
    <%= image_tag("example-slide-3.jpg") %>
    <%= image_tag("example-slide-4.jpg") %>
    </div>
  </div>
  <div>
  <h1>Big Time Production</h1>
  <h2>Commercial Director Portfolio Site</h2>
  <div class="container">
    <div id="slider" class="flexslider">
      <ul class="slides">
        <li>
          <%= image_tag("slide1.jpg") %>
        </li>
        <li>
          <%= image_tag("slide2.jpg") %>
        </li>
        <li>
          <%= image_tag("slide3.jpg") %>
        </li>
        <li>
          <%= image_tag("slide4.jpg") %>
        </li>
      </ul>
  </div>
  <div id="carousel" class="flexslider">
     <ul class="slides">
        <li>
          <%= image_tag("slide1.jpg") %>
        </li>
        <li>
          <%= image_tag("slide2.jpg") %>
        </li>
        <li>
          <%= image_tag("slide3.jpg") %>
        </li>
        <li>
          <%= image_tag("slide4.jpg") %>
        </li>
      </ul>
  </div>
  <p>longer project description</p>
  <h2>Technologies:</h2>
  <ul>
    <li>Ruby on Rails</li>
    <li>HTML5</li>
    <li>CSS3</li>
  </ul>
  </div>
  <div>
  <h1>Project Two</h1>
  <h2> one line description</h2>
   <div class="container">
<div id="slider_two" class="flexslider">
  <ul class="slides">
    <li>
    <%= image_tag("slide1.jpg") %>
    </li>
    <li>
    <%= image_tag("slide2.jpg") %>
    </li>
    <li>
    <%= image_tag("slide3.jpg") %>
    </li>
    <li>
    <%= image_tag("slide4.jpg") %>
    </li>
  </ul>
</div>
<div id="carousel_two" class="flexslider">
  <ul class="slides">
    <li>
    <%= image_tag("slide1.jpg") %>
    </li>
    <li>
    <%= image_tag("slide2.jpg") %>
    </li>
    <li>
    <%= image_tag("slide3.jpg") %>
    </li>
    <li>
    <%= image_tag("slide4.jpg") %>
    </li>
  </ul>
</div>
  <p>longer project description</p>
  <h2>Technologies:</h2>
  <ul>
    <li>Ruby on Rails</li>
    <li>HTML5</li>
    <li>CSS3</li>
  </ul>
  </div>
  <div>
  <h1>Project Three</h1>
  <h2> one line description</h2>
   <div class="container">
<div id="slider_three" class="flexslider">
  <ul class="slides">
    <li>
    <%= image_tag("slide1.jpg") %>
    </li>
    <li>
    <%= image_tag("slide2.jpg") %>
    </li>
    <li>
    <%= image_tag("slide3.jpg") %>
    </li>
    <li>
    <%= image_tag("slide4.jpg") %>
    </li>
  </ul>
</div>
<div id="carousel_three" class="flexslider">
  <ul class="slides">
    <li>
    <%= image_tag("slide1.jpg") %>
    </li>
    <li>
    <%= image_tag("slide2.jpg") %>
    </li>
    <li>
    <%= image_tag("slide3.jpg") %>
    </li>
    <li>
    <%= image_tag("slide4.jpg") %>
    </li>
  </ul>
</div>
  <p>longer project description</p>
  <h2>Technologies:</h2>
  <ul>
    <li>Ruby on Rails</li>
    <li>HTML5</li>
    <li>CSS3</li>
  </ul>
  </div>
</body>
<script>
$(window).load(function() {
  // The slider being synced must be initialized first
  $('#carousel').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    itemWidth: 210,
    itemMargin: 5,
    asNavFor: '#slider'
  });
   
  $('#slider').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    sync: "#carousel"
  });

   $('#carousel_two').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    itemWidth: 210,
    itemMargin: 5,
    asNavFor: '#slider_two'
  });
   
  $('#slider_two').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    sync: "#carousel_two"
  });

   $('#carousel_three').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    itemWidth: 210,
    itemMargin: 5,
    asNavFor: '#slider_three'
  });
   
  $('#slider_three').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    sync: "#carousel_three"
  });
});


</script>
</html>

app/views/home/new.html.erb
<h1>New home</h1>

<%= render 'form' %>

<%= link_to 'Back', home_index_path %>

app/views/home/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', home_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PortfolioSite" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>


   <div class="container">
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
    </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Jackson Sandland 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/resume/_form.html.erb
<%= form_for(@resume) do |f| %>
  <% if @resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% @resume.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resume/edit.html.erb
<h1>Editing resume</h1>

<%= render 'form' %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resume_index_path %>

app/views/resume/index.html.erb
<h1>Listing resume</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @resume.each do |resume| %>
      <tr>
        <td><%= link_to 'Show', resume %></td>
        <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
        <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resume', new_resume_path %>

app/views/resume/new.html.erb
<h1>New resume</h1>

<%= render 'form' %>

<%= link_to 'Back', resume_index_path %>

app/views/resume/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_resume_path(@resume) %> |
<%= link_to 'Back', resume_index_path %>